POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 1234,
    "details": "Um evento para programação para uma pessoa",
    "maximumAttendees":1
}

###

POST http://localhost:3333/events/67e7b625-bced-4782-af3a-b500ca5f11a5/attendees
Content-Type: application/json

{
    "name": "Adolfo Machado",
    "email": "adolfo2@email.com"
}

###

POST http://localhost:3333/events/9208046d-6a8c-4004-b5d4-a11c869e45cf/attendees
Content-Type: application/json

{
    "name": "Adolfo Machado",
    "email": "adolfo2@email.com"
}

###

GET  http://localhost:3333/events/9208046d-6a8c-4004-b5d4-a11c869e45cf

###

GET  http://localhost:3333/events/67e7b625-bced-4782-af3a-b500ca5f11a5

###

GET  http://localhost:3333/attendees/5/badge

###

GET http://localhost:3333/attendees/1/check-in


###

GET  http://localhost:3333/events/67e7b625-bced-4782-af3a-b500ca5f11a5/attendees


###

GET  http://localhost:3333/events/67e7b625-bced-4782-af3a-b500ca5f11a5/attendees?query=adolfo